repos:
- repo: https://github.com/omnilib/ufmt
  rev: v2.2.0
  hooks:
    - id: ufmt
      additional_dependencies:
        - black == 23.3.0
        - usort == 1.0.7

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.13.0'
  hooks:
    - id: ruff-check
